[package]
name = "rust-wasm"
version = "0.0.1"
authors = ["Marc Anderson"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "*"
js-sys = "*"

[dev-dependencies]
wasm-bindgen-test = "*"

[dependencies.web-sys]
version = "*"
features = [
  'console',
  'Document',
  'Element',
  'HtmlElement',
  'Node',
  'Window',
]